### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by robinvd** [robinvd/telegram-bot#1]
- [ ] parse students into a list of students instead of a string
- [ ] alllow a command to send multiple messages back
- [ ] small cleanups, annotated with "(TODO)" in the code
- [ ] timer, to send a message every morning
- [ ] ignore activities in the past
- [ ] ability to show multiple days
- [ ] update the README to reflect the last changes
- [ ] move to TVars instead of MVars
- [ ] use Mvars(/Tvars) for updateId,settings
- [ ] interactivity while running (change token, settings)
- [ ] move to a non empty list type for the arguments
- [ ] caching the rug timetables
